- name: copy file 
  copy: src=files/admin-openrc dest=/root/admin-openrc

- name: Create a service project
  keystone:
    command: "ensure_project"
    domain_name: "Default"
    description: "Service project"
    endpoint: "http://controller:35357/v3"
    project_name: "service"
    token: "123456"

- name: Create a demo project
  keystone:
    command: "ensure_project"
    project_name: "demo"
    domain_name: "Default"
    description: "Demo project"

- name: Create the demo user
  keystone:
    command: "ensure_user"
    domain_name: "Default"
    user_name: "demo"
    password: "123456"

- name: Create the user role
  keystone:
    command: "ensure_user"
    role_name: "user"

- name: Add the user role to the demo project and user
  keystone:
    command: "ensure_user_role"
    project_name: "demo"
    role_name: "user"
    user_name: "demo"


