- name: add admin-openrc file
  copy: src=files/admin-openrc dest=/root/admin-openrc

- name: source admin-openrc
  shell: source /root/admin-openrc

- name: create a domain,projects,users and roles
  shell: |
      openstack project create --domain default --description "Service Project" service
      openstack project create --domain default --description "Demo Project" demo
      openstack user create --domain default --password-prompt demo
      openstack role create user
      openstack role add --project demo --user demo user
