- name: install rabbitmq
  yum: name=rabbitmq-server state=installed

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started enabled=yes

- name: useradd openstack 
  shell: rabbitmqctl add_user openstack 123456 && rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  ignore_errors: true
