- name: install sql
  yum: name={{item}} state=installed
  with_items:
      - mariadb
      - mariadb-server
      - python2-PyMySQL

- name: add mariadb_openstack.cnf file
  copy: src=./files/mariadb_openstack.cnf dest=/etc/my.cnf.d/

- name: change database password
  command: mysqladmin -u root password 123456

- name: restart mariadb
  service: name=mariadb state=started enabled=yes
