- name: install openstack 
  gather_facts: no
  hosts: all
  vars_files:
      - ./group_vars/all.yml
  roles:
#     - Environment
#     - Identity
#     - Image
#     - Compute
     - Network
     - Dashboard

