- name: Create the nova_api, nova, and nova_cell0 databases
  mysql_user: name={{ item  }} login_user=root login_password=123456 state=present
  with_items:
      - nova_api
      - nova
      - nova_cell0

- name: Grant proper access to nova_api databases 
  mysql_user:
      login_user: root
      login_password: 123456
      name: nova_api
      password: 123456
      host: "{{ item }}"
      state: present
      priv: "nova_api.*:ALL,GRANT"
  with_items:
      - "localhost"
      - "%"

- name: Grant proper access to nova databases
  mysql_user:
      login_user: root
      login_password: 123456
      name: nova
      password: 123456
      host: "{{ item }}"
      state: present
      priv: "nova.*:ALL,GRANT"
  with_items:
      - "localhost"
      - "%"

- name: Grant proper access to nova_cell0 databases
  mysql_user:
      login_user: root
      login_password: 123456
      name: nova_cell0
      password: 123456
      host: "{{ item }}"
      state: present
      priv: "nova_cell0.*:ALL,GRANT"
  with_items:
      - "localhost"
      - "%"

- name: Create the nova user
  template: src=templates/create_nova_user.j2 dest=/root/create_nova_user.sh mode=777

- name: Create the nova user
  command: bash /root/create_nova_user.sh

- name: Add the admin role to the nova user
  command: source /root/admin-openrc && openstack role add --project service --user nova admin

- name: Create the Compute API service endpoints
  template: src=templates/create_compute_api.j2 dest=/root/create_compute_api.sh mode=777

- name: Create compute api endpoints
  command: bash /root/create_compute_api.sh

- name: Create a Placement service user
  template: templates/create_placement_service.j2 dest=/root/create_placement_service.sh mode=777

- name: Create a Placement service user 
  command: bash /root/create_placement_service.sh

- name: Add the Placement user to the service project with the admin role
  command: source /root/admin-openrc && openstack role add --project service --user placement admin

- name: Create the Placement API service and endpoint
  template: src=templates/create_plancement_api.j2 dest=/root/create_plancement_api.sh mode=777

- name: Create the Placement API service and endpoint
  command: bash /root/create_plancement_api.sh

#Install package and edit file
- name: Install the nova packages
  yum: name={{item}} state=installed
  with_items:
      - openstack-nova-api
      - openstack-nova-conductor
      - openstack-nova-console
      - openstack-nova-novncproxy
      - openstack-nova-scheduler
      - openstack-nova-placement-api


